import dynamic from 'next/dynamic'
import Head from 'next/head'


const Body = dynamic(() => import('../components/Body'), { ssr: false })
export const getStaticProps = () => ({ props: { basePath: process.env.BASE_PATH } })

const Home = ({ basePath }) => (
  <div>
    <Head>
      <title>DHIS SMS Logs</title>
      <meta name='description' content='Generated by create next app' />
      <link rel='icon' href='/favicon.ico' />
    </Head>
    <Body basePath={basePath} />
  </div>
)

export default Home